### ISSUE TITLE
Accountcreationlambdacfn.YAML is not working

### ISSUE THREAD

**Issue by vinodkumar4b9** [aws-samples/aws-account-vending-machine#1]
Hi team,

When i have deployed the solution using the CFN template  Accountcreationlambdacfn.YAML , It is giving me the error and Lambda functions is not getting created 

"AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException" and even s3 bucket is not able to access 

I have modified the template regarding Account builder lambda as below

Resources:

  AccountBuilderLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: LambdaExecuteRole
    Properties:
      Handler: "AccountCreationLambda.main"
      Runtime: "python3.6"
      Role: !GetAtt LambdaExecuteRole.Arn
      Timeout: 800
      TracingConfig:
          Mode: "Active"
      Code:
        S3Bucket: "aws-avm-ohio123"
        S3Key: "AccountCreationLambda.zip"

and even the cloudformation tenmplate is missing transfrom function  as below 

**Transform: AWS::Serverless-2016-10-31**

**Comment by khastation** [comment]
Code: 400; Error Code: InvalidParameterValueException
We've retested the template and it works as expected. Please debug the param values and make sure the files, buckets you reference exist in the correct region.
