### ISSUE TITLE
Account provisioned without completing baseline configurations

### ISSUE THREAD

**Issue by rajgandhi9** [aws-samples/aws-account-vending-machine#11]
Tried to create an account using the Service Catalog - Account Vending Machine product. A new account was provisioned, however, the Lambda function failed with the following error:

```
local variable 'r' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
  File "/var/task/AccountCreationLambda.py", line 341, in main
    print("An error occured: 
{}
. Error Stack: 
{}
".format(r,e))
UnboundLocalError: local variable 'r' referenced before assignment
```

Due the Lambda failure: 
- the account wasn't moved under the designated OU 
- and the default VPCs weren't deleted.

**Comment by khastation** [comment]
@rajgandhi9 are you still facing this error?
