### ISSUE TITLE
Python Runtime "3.6" doesn't work 

### ISSUE THREAD

**Issue by iamndash** [aws-samples/aws-account-vending-machine#16]
Hi,

Python runtime 3.6 is not supported any more. Must be change to 3.9 for below files.

aws-account-vending-machine/govcloud/commercial-side-setup/CommercialAccountSetup.yaml (line#36)
aws-account-vending-machine/govcloud/govcloud-side-setup/GovCloudAccountSetup.yaml (line#47)

Thanks,
ND

**Comment by vinaykuchibhotla** [comment]
Added support

**Comment by vinaykuchibhotla** [comment]
Added support
