### ISSUE TITLE
Create stack failing due to GetObject. S3 Error Code: NoSuchKey

### ISSUE THREAD

**Issue by mullamalibasha** [aws-samples/aws-account-vending-machine#23]
While creating the stack we are getting below error. Please help me on this.
Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: Lambda, Status Code: 400, Request ID: ad9bb8d6-5c12-432e-8438-8584ce7c9024)" (RequestToken: fe23dc9c-f282-baaf-a281-8b99d4caf956, HandlerErrorCode: InvalidRequest)

**Comment by khastation** [comment]
Hi @mullamalibasha - this means that the IAM role for the lambda function does not have `GetObject` access to the S3 bucket where your code resides. Once you enable access using the S3 bucket policy/IAM role, this error should go away.

**Comment by mullamalibasha** [comment]
Hi @khastation I have provided s3 full access to lambda function, still getting same issue.
