### ISSUE TITLE
Absention of move_account to given OU

### ISSUE THREAD

**Issue by o2346** [aws-samples/aws-account-vending-machine#3]
Hi team

I found following functionality in `AccountCreationLambda.py` is absent.

> If provided, creates an organization unit under the root account in AWS Organizations.
> Moves the newly created account from the organization root to the newly created organizational unit.
(according to README.md)

source:
https://github.com/aws-samples/aws-account-vending-machine/blob/master/resources/AccountCreationLambda.py#L52
https://github.com/aws-samples/aws-account-vending-machine/blob/master/resources/AccountCreationLambda.py#L202
(`get_ou_name_id` is defined but seemed to be never called)

Actually it did not work as expected in my environment. Even name for OU was given in parameter at provision-product on Service Catalog and the lambda function invocation was occured, still the account remains on root unexpectedly.

I wonder why this proposed functionality was absent in your source AccountCreationLambda.py. Anyway though, In order to make it functional, I updated the lambda function like shown below then it did work.

#2

Or else, any potential reason to be cautious for update?
I would appreciate for your consideration.
Thanks

**Comment by khastation** [comment]
This is now fixed with the latest commit [07f9c9cf68786209d6dc6bbb645ef5af7ab15380](https://github.com/aws-samples/aws-account-vending-machine/commit/07f9c9cf68786209d6dc6bbb645ef5af7ab15380)
