### ISSUE TITLE
Newly created account is neglected at failure of `get_ou_name_id`

### ISSUE THREAD

**Issue by o2346** [aws-samples/aws-account-vending-machine#5]
Current implementation [exits](https://github.com/aws-samples/aws-account-vending-machine/blob/master/resources/AccountCreationLambda.py#L319) before completion of its tasks at some kind of exception such as #4.
Here I mean 'tasks' like deleting default VPCs, executing cloudformation with baseline template on the newly created account.

currently:

```
Create new account
↓
Move account to OU provided
↓
exit on faliure
↓
newly created account was neglected without processing tasks supposed to be done
```

This is what I'm unhappy because being forced to clean up such half-baked account, no matter why.
I think it would be helpful if such challengings caused by exceptions were minimized as much as possible.

desirable:

```
get_ou_name_id as provided
↓
(exit if faliure)
↓
Create new account
↓
Move account to the OU provided
```

In this sequence, There would at least be no half-baked account on failure of `get_ou_name_id`.

Or else, could it just continue follwing tasks at any rate instead?
(No matter successful or failure for OU, If we could assume the tasks are isolated from what parent currently is)
Since I guess same issue would also occurs at faliure of 'Move account'.

Thanks

**Comment by khastation** [comment]
@o2346 were you able to fix this issue? If yes, feel free to open a PR. We haven't seen others report this yet.
