### ISSUE TITLE
NoSuchBucket error during AVM deployment

### ISSUE THREAD

**Issue by toytown** [aws-samples/aws-account-vending-machine#6]
I created an S3 bucket but still getting the error below. There is no logs to trace where the issue is

AccountBuilderLambda | CREATE_FAILED | Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 72eddeb5-9db9-41a7-809b-d77e3c2a5463)
-- | -- | --

**Comment by praveenchaks** [comment]
Faced the same issue. You've to change the bucket name in few places inside the yaml codes. Otherwise just go with the default bucket provided in the CFN template.

**Comment by khastation** [comment]
Adding to the response by @praveenchaks. 

The code works as expected for the default Amazon S3 bucket provided in the solution. If you want to use your own S3 bucket, upload the resources in this repo to your bucket, and make the required changes in your AWS CloudFormation template where the default bucket is referenced. 

Considering this issue closed, please reopen if you continue to face issues.
